apiVersion: apps/v1
kind: Deployment
metadata:
  name: reacher-backend
spec:
  replicas: 95
  selector:
    matchLabels:
      app: reacher
  template:
    metadata:
      labels:
        app: reacher
    spec:
      containers:
      - name: reacher-backend
        image: reacherhq/backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reacher-service
spec:
  selector:
    app: reacher
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090  # Must be in 30000-32767

